import Head from "next/head";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Container, LogoutButn, Navbar } from "@/styles/Todo.styled";
import { Button, SignupButton, Title } from "@/styles/Auth.styled";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar>
        <Title htmlFor="fname">ToDo</Title>
        <div>
          <Link href={"/login"}>Login</Link>
          <Link href={"/signup"}>
            <SignupButton>Create Account</SignupButton>
          </Link>
        </div>
      </Navbar>
      <Container>
        <h1>Write ToDos and forget to work on them as usual :D</h1>
      </Container>
    </>
  );
}
